ALTER TABLE EMRA_PLAN_TECNICO ADD (CONSTRAINT Constraint de sistema "C_TECNICO_ID" IS NOT NULL);

ALTER TABLE EMRA_PLAN_TECNICO ADD (CONSTRAINT Constraint de sistema "C_TECNICO_ID" IS NOT NULL);

ALTER TABLE EMRA_PLAN_TECNICO ADD (CONSTRAINT Constraint de sistema "C_TECNICO_ID" IS NOT NULL);

