ALTER TABLE EMRA_TRABAJOS MODIFY (N_EXP  NOT NULL);
ALTER TABLE EMRA_TRABAJOS MODIFY (N_EXP  NOT NULL);
ALTER TABLE EMRA_TRABAJOS MODIFY (N_EXP  NOT NULL);
ALTER TABLE EMRA_TRABAJOS MODIFY (N_EXP  NOT NULL);
ALTER TABLE EMRA_TRABAJOS ADD (CONSTRAINT Constraint de sistema "N_EXP" IS NOT NULL);

ALTER TABLE EMRA_TRABAJOS MODIFY (N_EXP  NOT NULL);
ALTER TABLE EMRA_TRABAJOS ADD (CONSTRAINT Constraint de sistema "N_EXP" IS NOT NULL);

ALTER TABLE EMRA_TRABAJOS MODIFY (N_EXP  NOT NULL);
ALTER TABLE EMRA_TRABAJOS ADD (CONSTRAINT Constraint de sistema "N_EXP" IS NOT NULL);

