ALTER TABLE EMRA_PLAN_REC_PREVEN MODIFY (C_TIPO_REC_PREVEN VARCHAR2(2));
ALTER TABLE EMRA_PLAN_REC_PREVEN MODIFY (C_TIPO_REC_PREVEN VARCHAR2(2));
ALTER TABLE EMRA_PLAN_REC_PREVEN MODIFY (C_TIPO_REC_PREVEN VARCHAR2(2));
ALTER TABLE EMRA_PLAN_REC_PREVEN MODIFY (C_TIPO_REC_PREVEN VARCHAR2(2));
ALTER TABLE EMRA_PLAN_REC_PREVEN MODIFY (C_TIPO_REC_PREVEN VARCHAR2(2));
ALTER TABLE EMRA_PLAN_REC_PREVEN MODIFY (C_TIPO_REC_PREVEN VARCHAR2(2));
