ALTER TABLE EMRA_PLAN_ANEXO MODIFY (C_DOCUMENTO_ID  NOT NULL, C_SCGD_CAT_DOC NUMBER(2, 0), C_TIPO_ANEXO  NOT NULL);
ALTER TABLE EMRA_PLAN_ANEXO MODIFY (C_DOCUMENTO_ID  NOT NULL, C_SCGD_CAT_DOC NUMBER(2, 0), C_TIPO_ANEXO  NOT NULL);
ALTER TABLE EMRA_PLAN_ANEXO MODIFY (C_DOCUMENTO_ID  NOT NULL, C_SCGD_CAT_DOC NUMBER(2, 0), C_TIPO_ANEXO  NOT NULL);
ALTER TABLE EMRA_PLAN_ANEXO MODIFY (C_DOCUMENTO_ID  NOT NULL, C_SCGD_CAT_DOC NUMBER(2, 0), C_TIPO_ANEXO  NOT NULL);
ALTER TABLE EMRA_PLAN_ANEXO ADD (CONSTRAINT Constraint de sistema "C_TIPO_ANEXO" IS NOT NULL);

ALTER TABLE EMRA_PLAN_ANEXO MODIFY (C_DOCUMENTO_ID  NOT NULL, C_SCGD_CAT_DOC NUMBER(2, 0), C_TIPO_ANEXO  NOT NULL);
ALTER TABLE EMRA_PLAN_ANEXO ADD (CONSTRAINT Constraint de sistema "C_TIPO_ANEXO" IS NOT NULL);

ALTER TABLE EMRA_PLAN_ANEXO MODIFY (C_DOCUMENTO_ID  NOT NULL, C_SCGD_CAT_DOC NUMBER(2, 0), C_TIPO_ANEXO  NOT NULL);
ALTER TABLE EMRA_PLAN_ANEXO ADD (CONSTRAINT Constraint de sistema "C_TIPO_ANEXO" IS NOT NULL);

