ALTER TABLE EMRA_AUTORIDAD_LABORAL ADD (CONSTRAINT Constraint de sistema "C_PROV" IS NOT NULL);

ALTER TABLE EMRA_AUTORIDAD_LABORAL ADD (CONSTRAINT Constraint de sistema "C_PROV" IS NOT NULL);

ALTER TABLE EMRA_AUTORIDAD_LABORAL ADD (CONSTRAINT Constraint de sistema "C_PROV" IS NOT NULL);

