ALTER TABLE EMRA_BAJA ADD (CONSTRAINT Constraint de sistema "C_BAJA_ID" IS NOT NULL);

ALTER TABLE EMRA_BAJA ADD (CONSTRAINT Constraint de sistema "C_BAJA_ID" IS NOT NULL);

ALTER TABLE EMRA_BAJA ADD (CONSTRAINT Constraint de sistema "C_BAJA_ID" IS NOT NULL);

