CREATE SEQUENCE EMRA_SEC_BAJA;
CREATE SEQUENCE EMRA_SEC_PLAN_REC_PREVEN;

CREATE SEQUENCE EMRA_SEC_BAJA;
CREATE SEQUENCE EMRA_SEC_PLAN_REC_PREVEN;

CREATE SEQUENCE EMRA_SEC_BAJA;
CREATE SEQUENCE EMRA_SEC_PLAN_REC_PREVEN;

