DROP SYNONYM PLAN_TECNICO;

CREATE SYNONYM P_FISICAS FOR CACT.CACT_P_FISICAS;
CREATE SYNONYM BAJA FOR EMRA.EMRA_BAJA;
CREATE SYNONYM BAJA_ANEXO FOR EMRA.EMRA_BAJA_ANEXO;
CREATE SYNONYM ENVIO FOR EMRA.EMRA_ENVIO;
CREATE SYNONYM PLAN_REC_PREVEN FOR EMRA.EMRA_PLAN_REC_PREVEN;
CREATE SYNONYM SEC_BAJA FOR EMRA.EMRA_SEC_BAJA;
CREATE SYNONYM SEC_PLAN_REC_PREVEN FOR EMRA.EMRA_SEC_PLAN_REC_PREVEN;
CREATE SYNONYM SOLICITUD_ANEXO FOR EMRA.EMRA_SOLICITUD_ANEXO;
CREATE SYNONYM TIPO_ENVIO FOR EMRA.EMRA_TIPO_ENVIO;
CREATE SYNONYM VARIACION_ANEXO FOR EMRA.EMRA_VARIACION_ANEXO;

