ALTER TABLE REAC_P_JURIDICAS_REA ADD (AUTONOMIA_INSCRIPCION VARCHAR2(2000), B_CARGADO VARCHAR2(1) DEFAULT 'N');
ALTER TABLE REAC_P_JURIDICAS_REA MODIFY (ID  NULL);
ALTER TABLE REAC_P_JURIDICAS_REA ADD (CONSTRAINT PKPJURREA PRIMARY KEY (Lista de campos));

ALTER TABLE REAC_P_JURIDICAS_REA ADD (AUTONOMIA_INSCRIPCION VARCHAR2(2000), B_CARGADO VARCHAR2(1) DEFAULT 'N');
ALTER TABLE REAC_P_JURIDICAS_REA MODIFY (ID  NULL);
ALTER TABLE REAC_P_JURIDICAS_REA ADD (CONSTRAINT PKPJURREA PRIMARY KEY (Lista de campos));

ALTER TABLE REAC_P_JURIDICAS_REA ADD (AUTONOMIA_INSCRIPCION VARCHAR2(2000), B_CARGADO VARCHAR2(1) DEFAULT 'N');
ALTER TABLE REAC_P_JURIDICAS_REA MODIFY (ID  NULL);
ALTER TABLE REAC_P_JURIDICAS_REA ADD (CONSTRAINT PKPJURREA PRIMARY KEY (Lista de campos));

ALTER TABLE REAC_P_JURIDICAS_REA ADD (AUTONOMIA_INSCRIPCION VARCHAR2(2000), B_CARGADO VARCHAR2(1) DEFAULT 'N');
ALTER TABLE REAC_P_JURIDICAS_REA MODIFY (ID  NULL);
ALTER TABLE REAC_P_JURIDICAS_REA ADD (CONSTRAINT PKPJURREA PRIMARY KEY (Lista de campos));

ALTER TABLE REAC_P_JURIDICAS_REA ADD (AUTONOMIA_INSCRIPCION VARCHAR2(2000), B_CARGADO VARCHAR2(1) DEFAULT 'N');
ALTER TABLE REAC_P_JURIDICAS_REA MODIFY (ID  NULL);
ALTER TABLE REAC_P_JURIDICAS_REA ADD (CONSTRAINT PKPJURREA PRIMARY KEY (Lista de campos));

ALTER TABLE REAC_P_JURIDICAS_REA ADD (AUTONOMIA_INSCRIPCION VARCHAR2(2000), B_CARGADO VARCHAR2(1) DEFAULT 'N');
ALTER TABLE REAC_P_JURIDICAS_REA MODIFY (ID  NULL);
ALTER TABLE REAC_P_JURIDICAS_REA ADD (CONSTRAINT PKPJURREA PRIMARY KEY (Lista de campos));

ALTER TABLE REAC_P_JURIDICAS_REA ADD (AUTONOMIA_INSCRIPCION VARCHAR2(2000), B_CARGADO VARCHAR2(1) DEFAULT 'N');
ALTER TABLE REAC_P_JURIDICAS_REA MODIFY (ID  NULL);
ALTER TABLE REAC_P_JURIDICAS_REA ADD (CONSTRAINT PKPJURREA PRIMARY KEY (Lista de campos));

ALTER TABLE REAC_P_JURIDICAS_REA ADD (AUTONOMIA_INSCRIPCION VARCHAR2(2000), B_CARGADO VARCHAR2(1) DEFAULT 'N');
ALTER TABLE REAC_P_JURIDICAS_REA MODIFY (ID  NULL);
ALTER TABLE REAC_P_JURIDICAS_REA ADD (CONSTRAINT PKPJURREA PRIMARY KEY (Lista de campos));

ALTER TABLE REAC_P_JURIDICAS_REA ADD (AUTONOMIA_INSCRIPCION VARCHAR2(2000), B_CARGADO VARCHAR2(1) DEFAULT 'N');
ALTER TABLE REAC_P_JURIDICAS_REA MODIFY (ID  NULL);
ALTER TABLE REAC_P_JURIDICAS_REA ADD (CONSTRAINT PKPJURREA PRIMARY KEY (Lista de campos));

ALTER TABLE REAC_P_JURIDICAS_REA ADD (AUTONOMIA_INSCRIPCION VARCHAR2(2000), B_CARGADO VARCHAR2(1) DEFAULT 'N');
ALTER TABLE REAC_P_JURIDICAS_REA MODIFY (ID  NULL);
ALTER TABLE REAC_P_JURIDICAS_REA ADD (CONSTRAINT PKPJURREA PRIMARY KEY (Lista de campos));

ALTER TABLE REAC_P_JURIDICAS_REA ADD (AUTONOMIA_INSCRIPCION VARCHAR2(2000), B_CARGADO VARCHAR2(1) DEFAULT 'N');
ALTER TABLE REAC_P_JURIDICAS_REA MODIFY (ID  NULL);
ALTER TABLE REAC_P_JURIDICAS_REA ADD (CONSTRAINT PKPJURREA PRIMARY KEY (Lista de campos));

ALTER TABLE REAC_P_JURIDICAS_REA ADD (AUTONOMIA_INSCRIPCION VARCHAR2(2000), B_CARGADO VARCHAR2(1) DEFAULT 'N');
ALTER TABLE REAC_P_JURIDICAS_REA MODIFY (ID  NULL);
ALTER TABLE REAC_P_JURIDICAS_REA ADD (CONSTRAINT PKPJURREA PRIMARY KEY (Lista de campos));

ALTER TABLE REAC_P_JURIDICAS_REA ADD (AUTONOMIA_INSCRIPCION VARCHAR2(2000), B_CARGADO VARCHAR2(1) DEFAULT 'N');
ALTER TABLE REAC_P_JURIDICAS_REA MODIFY (ID  NULL);
ALTER TABLE REAC_P_JURIDICAS_REA ADD (CONSTRAINT PKPJURREA PRIMARY KEY (Lista de campos));

ALTER TABLE REAC_P_JURIDICAS_REA ADD (AUTONOMIA_INSCRIPCION VARCHAR2(2000), B_CARGADO VARCHAR2(1) DEFAULT 'N');
ALTER TABLE REAC_P_JURIDICAS_REA MODIFY (ID  NULL);
ALTER TABLE REAC_P_JURIDICAS_REA ADD (CONSTRAINT PKPJURREA PRIMARY KEY (Lista de campos));

