ALTER TABLE REAC_P_JURIDICAS DROP (N_TIPO_DOCU);
ALTER TABLE REAC_P_JURIDICAS ADD (A_TIPO_DOCU VARCHAR2(4), C_COMUNIDAD_INSCR VARCHAR2(2));
ALTER TABLE REAC_P_JURIDICAS MODIFY (A_ESTADO_INSCR VARCHAR2(20), A_MOTI_CANCELA VARCHAR2(50));
ALTER TABLE REAC_P_JURIDICAS DROP CONSTRAINT UKPJURNREA;

ALTER TABLE REAC_P_JURIDICAS ADD (CONSTRAINT FKPJCOCOMU01 FOREIGN KEY(Lista de campos) REFERENCES COMU.la otra tabla (lista de campos de la otra tabla));

ALTER TABLE REAC_P_JURIDICAS DROP CONSTRAINT FKPJURCN0901;
ALTER TABLE REAC_P_JURIDICAS ADD (CONSTRAINT FKPJURCN0901 FOREIGN KEY(Lista de campos) REFERENCES COMU.la otra tabla (lista de campos de la otra tabla))
ALTER TABLE REAC_P_JURIDICAS DROP (N_TIPO_DOCU);
ALTER TABLE REAC_P_JURIDICAS ADD (A_TIPO_DOCU VARCHAR2(4), C_COMUNIDAD_INSCR VARCHAR2(2));
ALTER TABLE REAC_P_JURIDICAS MODIFY (A_ESTADO_INSCR VARCHAR2(20), A_MOTI_CANCELA VARCHAR2(50));
ALTER TABLE REAC_P_JURIDICAS DROP CONSTRAINT UKPJURNREA;

ALTER TABLE REAC_P_JURIDICAS ADD (CONSTRAINT FKPJCOCOMU01 FOREIGN KEY(Lista de campos) REFERENCES COMU.la otra tabla (lista de campos de la otra tabla));

ALTER TABLE REAC_P_JURIDICAS DROP CONSTRAINT FKPJURCN0901;
ALTER TABLE REAC_P_JURIDICAS ADD (CONSTRAINT FKPJURCN0901 FOREIGN KEY(Lista de campos) REFERENCES COMU.la otra tabla (lista de campos de la otra tabla))
ALTER TABLE REAC_P_JURIDICAS DROP (N_TIPO_DOCU);
ALTER TABLE REAC_P_JURIDICAS ADD (A_TIPO_DOCU VARCHAR2(4), C_COMUNIDAD_INSCR VARCHAR2(2));
ALTER TABLE REAC_P_JURIDICAS MODIFY (A_ESTADO_INSCR VARCHAR2(20), A_MOTI_CANCELA VARCHAR2(50));
ALTER TABLE REAC_P_JURIDICAS DROP CONSTRAINT UKPJURNREA;

ALTER TABLE REAC_P_JURIDICAS ADD (CONSTRAINT FKPJCOCOMU01 FOREIGN KEY(Lista de campos) REFERENCES COMU.la otra tabla (lista de campos de la otra tabla));

ALTER TABLE REAC_P_JURIDICAS DROP CONSTRAINT FKPJURCN0901;
ALTER TABLE REAC_P_JURIDICAS ADD (CONSTRAINT FKPJURCN0901 FOREIGN KEY(Lista de campos) REFERENCES COMU.la otra tabla (lista de campos de la otra tabla))
ALTER TABLE REAC_P_JURIDICAS DROP (N_TIPO_DOCU);
ALTER TABLE REAC_P_JURIDICAS ADD (A_TIPO_DOCU VARCHAR2(4), C_COMUNIDAD_INSCR VARCHAR2(2));
ALTER TABLE REAC_P_JURIDICAS MODIFY (A_ESTADO_INSCR VARCHAR2(20), A_MOTI_CANCELA VARCHAR2(50));
ALTER TABLE REAC_P_JURIDICAS DROP CONSTRAINT UKPJURNREA;

ALTER TABLE REAC_P_JURIDICAS ADD (CONSTRAINT FKPJCOCOMU01 FOREIGN KEY(Lista de campos) REFERENCES COMU.la otra tabla (lista de campos de la otra tabla));

ALTER TABLE REAC_P_JURIDICAS DROP CONSTRAINT FKPJURCN0901;
ALTER TABLE REAC_P_JURIDICAS ADD (CONSTRAINT FKPJURCN0901 FOREIGN KEY(Lista de campos) REFERENCES COMU.la otra tabla (lista de campos de la otra tabla))
ALTER TABLE REAC_P_JURIDICAS DROP (N_TIPO_DOCU);
ALTER TABLE REAC_P_JURIDICAS ADD (A_TIPO_DOCU VARCHAR2(4), C_COMUNIDAD_INSCR VARCHAR2(2));
ALTER TABLE REAC_P_JURIDICAS MODIFY (A_ESTADO_INSCR VARCHAR2(20), A_MOTI_CANCELA VARCHAR2(50));
ALTER TABLE REAC_P_JURIDICAS DROP CONSTRAINT UKPJURNREA;

ALTER TABLE REAC_P_JURIDICAS ADD (CONSTRAINT FKPJCOCOMU01 FOREIGN KEY(Lista de campos) REFERENCES COMU.la otra tabla (lista de campos de la otra tabla));

ALTER TABLE REAC_P_JURIDICAS DROP CONSTRAINT FKPJURCN0901;
ALTER TABLE REAC_P_JURIDICAS ADD (CONSTRAINT FKPJURCN0901 FOREIGN KEY(Lista de campos) REFERENCES COMU.la otra tabla (lista de campos de la otra tabla))
ALTER TABLE REAC_P_JURIDICAS DROP (N_TIPO_DOCU);
ALTER TABLE REAC_P_JURIDICAS ADD (A_TIPO_DOCU VARCHAR2(4), C_COMUNIDAD_INSCR VARCHAR2(2));
ALTER TABLE REAC_P_JURIDICAS MODIFY (A_ESTADO_INSCR VARCHAR2(20), A_MOTI_CANCELA VARCHAR2(50));
ALTER TABLE REAC_P_JURIDICAS DROP CONSTRAINT UKPJURNREA;

ALTER TABLE REAC_P_JURIDICAS ADD (CONSTRAINT FKPJCOCOMU01 FOREIGN KEY(Lista de campos) REFERENCES COMU.la otra tabla (lista de campos de la otra tabla));

ALTER TABLE REAC_P_JURIDICAS DROP CONSTRAINT FKPJURCN0901;
ALTER TABLE REAC_P_JURIDICAS ADD (CONSTRAINT FKPJURCN0901 FOREIGN KEY(Lista de campos) REFERENCES COMU.la otra tabla (lista de campos de la otra tabla))
ALTER TABLE REAC_P_JURIDICAS DROP (N_TIPO_DOCU);
ALTER TABLE REAC_P_JURIDICAS ADD (A_TIPO_DOCU VARCHAR2(4), C_COMUNIDAD_INSCR VARCHAR2(2));
ALTER TABLE REAC_P_JURIDICAS MODIFY (A_ESTADO_INSCR VARCHAR2(20), A_MOTI_CANCELA VARCHAR2(50));
ALTER TABLE REAC_P_JURIDICAS DROP CONSTRAINT UKPJURNREA;

ALTER TABLE REAC_P_JURIDICAS ADD (CONSTRAINT FKPJCOCOMU01 FOREIGN KEY(Lista de campos) REFERENCES COMU.la otra tabla (lista de campos de la otra tabla));

ALTER TABLE REAC_P_JURIDICAS DROP CONSTRAINT FKPJURCN0901;
ALTER TABLE REAC_P_JURIDICAS ADD (CONSTRAINT FKPJURCN0901 FOREIGN KEY(Lista de campos) REFERENCES COMU.la otra tabla (lista de campos de la otra tabla))
ALTER TABLE REAC_P_JURIDICAS DROP (N_TIPO_DOCU);
ALTER TABLE REAC_P_JURIDICAS ADD (A_TIPO_DOCU VARCHAR2(4), C_COMUNIDAD_INSCR VARCHAR2(2));
ALTER TABLE REAC_P_JURIDICAS MODIFY (A_ESTADO_INSCR VARCHAR2(20), A_MOTI_CANCELA VARCHAR2(50));
ALTER TABLE REAC_P_JURIDICAS DROP CONSTRAINT UKPJURNREA;

ALTER TABLE REAC_P_JURIDICAS ADD (CONSTRAINT FKPJCOCOMU01 FOREIGN KEY(Lista de campos) REFERENCES COMU.la otra tabla (lista de campos de la otra tabla));

ALTER TABLE REAC_P_JURIDICAS DROP CONSTRAINT FKPJURCN0901;
ALTER TABLE REAC_P_JURIDICAS ADD (CONSTRAINT FKPJURCN0901 FOREIGN KEY(Lista de campos) REFERENCES COMU.la otra tabla (lista de campos de la otra tabla))
ALTER TABLE REAC_P_JURIDICAS DROP (N_TIPO_DOCU);
ALTER TABLE REAC_P_JURIDICAS ADD (A_TIPO_DOCU VARCHAR2(4), C_COMUNIDAD_INSCR VARCHAR2(2));
ALTER TABLE REAC_P_JURIDICAS MODIFY (A_ESTADO_INSCR VARCHAR2(20), A_MOTI_CANCELA VARCHAR2(50));
ALTER TABLE REAC_P_JURIDICAS DROP CONSTRAINT UKPJURNREA;

ALTER TABLE REAC_P_JURIDICAS ADD (CONSTRAINT FKPJCOCOMU01 FOREIGN KEY(Lista de campos) REFERENCES COMU.la otra tabla (lista de campos de la otra tabla));

ALTER TABLE REAC_P_JURIDICAS DROP CONSTRAINT FKPJURCN0901;
ALTER TABLE REAC_P_JURIDICAS ADD (CONSTRAINT FKPJURCN0901 FOREIGN KEY(Lista de campos) REFERENCES COMU.la otra tabla (lista de campos de la otra tabla))
ALTER TABLE REAC_P_JURIDICAS DROP (N_TIPO_DOCU);
ALTER TABLE REAC_P_JURIDICAS ADD (A_TIPO_DOCU VARCHAR2(4), C_COMUNIDAD_INSCR VARCHAR2(2));
ALTER TABLE REAC_P_JURIDICAS MODIFY (A_ESTADO_INSCR VARCHAR2(20), A_MOTI_CANCELA VARCHAR2(50));
ALTER TABLE REAC_P_JURIDICAS DROP CONSTRAINT UKPJURNREA;

ALTER TABLE REAC_P_JURIDICAS ADD (CONSTRAINT FKPJCOCOMU01 FOREIGN KEY(Lista de campos) REFERENCES COMU.la otra tabla (lista de campos de la otra tabla));

ALTER TABLE REAC_P_JURIDICAS DROP CONSTRAINT FKPJURCN0901;
ALTER TABLE REAC_P_JURIDICAS ADD (CONSTRAINT FKPJURCN0901 FOREIGN KEY(Lista de campos) REFERENCES COMU.la otra tabla (lista de campos de la otra tabla))
ALTER TABLE REAC_P_JURIDICAS DROP (N_TIPO_DOCU);
ALTER TABLE REAC_P_JURIDICAS ADD (A_TIPO_DOCU VARCHAR2(4), C_COMUNIDAD_INSCR VARCHAR2(2));
ALTER TABLE REAC_P_JURIDICAS MODIFY (A_ESTADO_INSCR VARCHAR2(20), A_MOTI_CANCELA VARCHAR2(50));
ALTER TABLE REAC_P_JURIDICAS DROP CONSTRAINT UKPJURNREA;

ALTER TABLE REAC_P_JURIDICAS ADD (CONSTRAINT FKPJCOCOMU01 FOREIGN KEY(Lista de campos) REFERENCES COMU.la otra tabla (lista de campos de la otra tabla));

ALTER TABLE REAC_P_JURIDICAS DROP CONSTRAINT FKPJURCN0901;
ALTER TABLE REAC_P_JURIDICAS ADD (CONSTRAINT FKPJURCN0901 FOREIGN KEY(Lista de campos) REFERENCES COMU.la otra tabla (lista de campos de la otra tabla))
ALTER TABLE REAC_P_JURIDICAS DROP (N_TIPO_DOCU);
ALTER TABLE REAC_P_JURIDICAS ADD (A_TIPO_DOCU VARCHAR2(4), C_COMUNIDAD_INSCR VARCHAR2(2));
ALTER TABLE REAC_P_JURIDICAS MODIFY (A_ESTADO_INSCR VARCHAR2(20), A_MOTI_CANCELA VARCHAR2(50));
ALTER TABLE REAC_P_JURIDICAS DROP CONSTRAINT UKPJURNREA;

ALTER TABLE REAC_P_JURIDICAS ADD (CONSTRAINT FKPJCOCOMU01 FOREIGN KEY(Lista de campos) REFERENCES COMU.la otra tabla (lista de campos de la otra tabla));

ALTER TABLE REAC_P_JURIDICAS DROP CONSTRAINT FKPJURCN0901;
ALTER TABLE REAC_P_JURIDICAS ADD (CONSTRAINT FKPJURCN0901 FOREIGN KEY(Lista de campos) REFERENCES COMU.la otra tabla (lista de campos de la otra tabla))
ALTER TABLE REAC_P_JURIDICAS DROP (N_TIPO_DOCU);
ALTER TABLE REAC_P_JURIDICAS ADD (A_TIPO_DOCU VARCHAR2(4), C_COMUNIDAD_INSCR VARCHAR2(2));
ALTER TABLE REAC_P_JURIDICAS MODIFY (A_ESTADO_INSCR VARCHAR2(20), A_MOTI_CANCELA VARCHAR2(50));
ALTER TABLE REAC_P_JURIDICAS DROP CONSTRAINT UKPJURNREA;

ALTER TABLE REAC_P_JURIDICAS ADD (CONSTRAINT FKPJCOCOMU01 FOREIGN KEY(Lista de campos) REFERENCES COMU.la otra tabla (lista de campos de la otra tabla));

ALTER TABLE REAC_P_JURIDICAS DROP CONSTRAINT FKPJURCN0901;
ALTER TABLE REAC_P_JURIDICAS ADD (CONSTRAINT FKPJURCN0901 FOREIGN KEY(Lista de campos) REFERENCES COMU.la otra tabla (lista de campos de la otra tabla))
ALTER TABLE REAC_P_JURIDICAS DROP (N_TIPO_DOCU);
ALTER TABLE REAC_P_JURIDICAS ADD (A_TIPO_DOCU VARCHAR2(4), C_COMUNIDAD_INSCR VARCHAR2(2));
ALTER TABLE REAC_P_JURIDICAS MODIFY (A_ESTADO_INSCR VARCHAR2(20), A_MOTI_CANCELA VARCHAR2(50));
ALTER TABLE REAC_P_JURIDICAS DROP CONSTRAINT UKPJURNREA;

ALTER TABLE REAC_P_JURIDICAS ADD (CONSTRAINT FKPJCOCOMU01 FOREIGN KEY(Lista de campos) REFERENCES COMU.la otra tabla (lista de campos de la otra tabla));

ALTER TABLE REAC_P_JURIDICAS DROP CONSTRAINT FKPJURCN0901;
ALTER TABLE REAC_P_JURIDICAS ADD (CONSTRAINT FKPJURCN0901 FOREIGN KEY(Lista de campos) REFERENCES COMU.la otra tabla (lista de campos de la otra tabla))
