ALTER TABLE REAC_CAMPO_REA ADD (B_AUTONOMIA VARCHAR2(1), B_CNAE VARCHAR2(1), B_ESTADO VARCHAR2(1) NOT NULL, B_LOCALIDAD VARCHAR2(1), B_PAIS VARCHAR2(1), B_PROVINCIA VARCHAR2(1), B_TIPO_DOCU VARCHAR2(1), N_ORDEN_EXCEL NUMBER(2, 0));
ALTER TABLE REAC_CAMPO_REA MODIFY (A_CAMPO VARCHAR2(30), A_CAMPO_REAC  NULL, A_FK VARCHAR2(2000), A_PROMPT  DEFAULT NULL);
ALTER TABLE REAC_CAMPO_REA ADD (CONSTRAINT UQCAREANEX UNIQUE (Lista de campos));

ALTER TABLE REAC_CAMPO_REA ADD (B_AUTONOMIA VARCHAR2(1), B_CNAE VARCHAR2(1), B_ESTADO VARCHAR2(1) NOT NULL, B_LOCALIDAD VARCHAR2(1), B_PAIS VARCHAR2(1), B_PROVINCIA VARCHAR2(1), B_TIPO_DOCU VARCHAR2(1), N_ORDEN_EXCEL NUMBER(2, 0));
ALTER TABLE REAC_CAMPO_REA MODIFY (A_CAMPO VARCHAR2(30), A_CAMPO_REAC  NULL, A_FK VARCHAR2(2000), A_PROMPT  DEFAULT NULL);
ALTER TABLE REAC_CAMPO_REA ADD (CONSTRAINT UQCAREANEX UNIQUE (Lista de campos));

ALTER TABLE REAC_CAMPO_REA ADD (B_AUTONOMIA VARCHAR2(1), B_CNAE VARCHAR2(1), B_ESTADO VARCHAR2(1) NOT NULL, B_LOCALIDAD VARCHAR2(1), B_PAIS VARCHAR2(1), B_PROVINCIA VARCHAR2(1), B_TIPO_DOCU VARCHAR2(1), N_ORDEN_EXCEL NUMBER(2, 0));
ALTER TABLE REAC_CAMPO_REA MODIFY (A_CAMPO VARCHAR2(30), A_CAMPO_REAC  NULL, A_FK VARCHAR2(2000), A_PROMPT  DEFAULT NULL);
ALTER TABLE REAC_CAMPO_REA ADD (CONSTRAINT UQCAREANEX UNIQUE (Lista de campos));

ALTER TABLE REAC_CAMPO_REA ADD (B_AUTONOMIA VARCHAR2(1), B_CNAE VARCHAR2(1), B_ESTADO VARCHAR2(1) NOT NULL, B_LOCALIDAD VARCHAR2(1), B_PAIS VARCHAR2(1), B_PROVINCIA VARCHAR2(1), B_TIPO_DOCU VARCHAR2(1), N_ORDEN_EXCEL NUMBER(2, 0));
ALTER TABLE REAC_CAMPO_REA MODIFY (A_CAMPO VARCHAR2(30), A_CAMPO_REAC  NULL, A_FK VARCHAR2(2000), A_PROMPT  DEFAULT NULL);
ALTER TABLE REAC_CAMPO_REA ADD (CONSTRAINT UQCAREANEX UNIQUE (Lista de campos));

ALTER TABLE REAC_CAMPO_REA ADD (B_AUTONOMIA VARCHAR2(1), B_CNAE VARCHAR2(1), B_ESTADO VARCHAR2(1) NOT NULL, B_LOCALIDAD VARCHAR2(1), B_PAIS VARCHAR2(1), B_PROVINCIA VARCHAR2(1), B_TIPO_DOCU VARCHAR2(1), N_ORDEN_EXCEL NUMBER(2, 0));
ALTER TABLE REAC_CAMPO_REA MODIFY (A_CAMPO VARCHAR2(30), A_CAMPO_REAC  NULL, A_FK VARCHAR2(2000), A_PROMPT  DEFAULT NULL);
ALTER TABLE REAC_CAMPO_REA ADD (CONSTRAINT UQCAREANEX UNIQUE (Lista de campos));

ALTER TABLE REAC_CAMPO_REA ADD (B_AUTONOMIA VARCHAR2(1), B_CNAE VARCHAR2(1), B_ESTADO VARCHAR2(1) NOT NULL, B_LOCALIDAD VARCHAR2(1), B_PAIS VARCHAR2(1), B_PROVINCIA VARCHAR2(1), B_TIPO_DOCU VARCHAR2(1), N_ORDEN_EXCEL NUMBER(2, 0));
ALTER TABLE REAC_CAMPO_REA MODIFY (A_CAMPO VARCHAR2(30), A_CAMPO_REAC  NULL, A_FK VARCHAR2(2000), A_PROMPT  DEFAULT NULL);
ALTER TABLE REAC_CAMPO_REA ADD (CONSTRAINT UQCAREANEX UNIQUE (Lista de campos));

ALTER TABLE REAC_CAMPO_REA ADD (B_AUTONOMIA VARCHAR2(1), B_CNAE VARCHAR2(1), B_ESTADO VARCHAR2(1) NOT NULL, B_LOCALIDAD VARCHAR2(1), B_PAIS VARCHAR2(1), B_PROVINCIA VARCHAR2(1), B_TIPO_DOCU VARCHAR2(1), N_ORDEN_EXCEL NUMBER(2, 0));
ALTER TABLE REAC_CAMPO_REA MODIFY (A_CAMPO VARCHAR2(30), A_CAMPO_REAC  NULL, A_FK VARCHAR2(2000), A_PROMPT  DEFAULT NULL);
ALTER TABLE REAC_CAMPO_REA ADD (CONSTRAINT UQCAREANEX UNIQUE (Lista de campos));

ALTER TABLE REAC_CAMPO_REA ADD (B_AUTONOMIA VARCHAR2(1), B_CNAE VARCHAR2(1), B_ESTADO VARCHAR2(1) NOT NULL, B_LOCALIDAD VARCHAR2(1), B_PAIS VARCHAR2(1), B_PROVINCIA VARCHAR2(1), B_TIPO_DOCU VARCHAR2(1), N_ORDEN_EXCEL NUMBER(2, 0));
ALTER TABLE REAC_CAMPO_REA MODIFY (A_CAMPO VARCHAR2(30), A_CAMPO_REAC  NULL, A_FK VARCHAR2(2000), A_PROMPT  DEFAULT NULL);
ALTER TABLE REAC_CAMPO_REA ADD (CONSTRAINT UQCAREANEX UNIQUE (Lista de campos));

ALTER TABLE REAC_CAMPO_REA ADD (B_AUTONOMIA VARCHAR2(1), B_CNAE VARCHAR2(1), B_ESTADO VARCHAR2(1) NOT NULL, B_LOCALIDAD VARCHAR2(1), B_PAIS VARCHAR2(1), B_PROVINCIA VARCHAR2(1), B_TIPO_DOCU VARCHAR2(1), N_ORDEN_EXCEL NUMBER(2, 0));
ALTER TABLE REAC_CAMPO_REA MODIFY (A_CAMPO VARCHAR2(30), A_CAMPO_REAC  NULL, A_FK VARCHAR2(2000), A_PROMPT  DEFAULT NULL);
ALTER TABLE REAC_CAMPO_REA ADD (CONSTRAINT UQCAREANEX UNIQUE (Lista de campos));

ALTER TABLE REAC_CAMPO_REA ADD (B_AUTONOMIA VARCHAR2(1), B_CNAE VARCHAR2(1), B_ESTADO VARCHAR2(1) NOT NULL, B_LOCALIDAD VARCHAR2(1), B_PAIS VARCHAR2(1), B_PROVINCIA VARCHAR2(1), B_TIPO_DOCU VARCHAR2(1), N_ORDEN_EXCEL NUMBER(2, 0));
ALTER TABLE REAC_CAMPO_REA MODIFY (A_CAMPO VARCHAR2(30), A_CAMPO_REAC  NULL, A_FK VARCHAR2(2000), A_PROMPT  DEFAULT NULL);
ALTER TABLE REAC_CAMPO_REA ADD (CONSTRAINT UQCAREANEX UNIQUE (Lista de campos));

ALTER TABLE REAC_CAMPO_REA ADD (B_AUTONOMIA VARCHAR2(1), B_CNAE VARCHAR2(1), B_ESTADO VARCHAR2(1) NOT NULL, B_LOCALIDAD VARCHAR2(1), B_PAIS VARCHAR2(1), B_PROVINCIA VARCHAR2(1), B_TIPO_DOCU VARCHAR2(1), N_ORDEN_EXCEL NUMBER(2, 0));
ALTER TABLE REAC_CAMPO_REA MODIFY (A_CAMPO VARCHAR2(30), A_CAMPO_REAC  NULL, A_FK VARCHAR2(2000), A_PROMPT  DEFAULT NULL);
ALTER TABLE REAC_CAMPO_REA ADD (CONSTRAINT UQCAREANEX UNIQUE (Lista de campos));

ALTER TABLE REAC_CAMPO_REA ADD (B_AUTONOMIA VARCHAR2(1), B_CNAE VARCHAR2(1), B_ESTADO VARCHAR2(1) NOT NULL, B_LOCALIDAD VARCHAR2(1), B_PAIS VARCHAR2(1), B_PROVINCIA VARCHAR2(1), B_TIPO_DOCU VARCHAR2(1), N_ORDEN_EXCEL NUMBER(2, 0));
ALTER TABLE REAC_CAMPO_REA MODIFY (A_CAMPO VARCHAR2(30), A_CAMPO_REAC  NULL, A_FK VARCHAR2(2000), A_PROMPT  DEFAULT NULL);
ALTER TABLE REAC_CAMPO_REA ADD (CONSTRAINT UQCAREANEX UNIQUE (Lista de campos));

ALTER TABLE REAC_CAMPO_REA ADD (B_AUTONOMIA VARCHAR2(1), B_CNAE VARCHAR2(1), B_ESTADO VARCHAR2(1) NOT NULL, B_LOCALIDAD VARCHAR2(1), B_PAIS VARCHAR2(1), B_PROVINCIA VARCHAR2(1), B_TIPO_DOCU VARCHAR2(1), N_ORDEN_EXCEL NUMBER(2, 0));
ALTER TABLE REAC_CAMPO_REA MODIFY (A_CAMPO VARCHAR2(30), A_CAMPO_REAC  NULL, A_FK VARCHAR2(2000), A_PROMPT  DEFAULT NULL);
ALTER TABLE REAC_CAMPO_REA ADD (CONSTRAINT UQCAREANEX UNIQUE (Lista de campos));

ALTER TABLE REAC_CAMPO_REA ADD (B_AUTONOMIA VARCHAR2(1), B_CNAE VARCHAR2(1), B_ESTADO VARCHAR2(1) NOT NULL, B_LOCALIDAD VARCHAR2(1), B_PAIS VARCHAR2(1), B_PROVINCIA VARCHAR2(1), B_TIPO_DOCU VARCHAR2(1), N_ORDEN_EXCEL NUMBER(2, 0));
ALTER TABLE REAC_CAMPO_REA MODIFY (A_CAMPO VARCHAR2(30), A_CAMPO_REAC  NULL, A_FK VARCHAR2(2000), A_PROMPT  DEFAULT NULL);
ALTER TABLE REAC_CAMPO_REA ADD (CONSTRAINT UQCAREANEX UNIQUE (Lista de campos));

