ALTER TABLE REAC_PJUR#ERROR ADD (A_COMENTARIO VARCHAR2(200));
ALTER TABLE REAC_PJUR#ERROR ADD (CONSTRAINT FKPJURPJUR01 FOREIGN KEY(Lista de campos) REFERENCES REAC.la otra tabla (lista de campos de la otra tabla));

ALTER TABLE REAC_PJUR#ERROR ADD (A_COMENTARIO VARCHAR2(200));
ALTER TABLE REAC_PJUR#ERROR ADD (CONSTRAINT FKPJURPJUR01 FOREIGN KEY(Lista de campos) REFERENCES REAC.la otra tabla (lista de campos de la otra tabla));

ALTER TABLE REAC_PJUR#ERROR ADD (A_COMENTARIO VARCHAR2(200));
ALTER TABLE REAC_PJUR#ERROR ADD (CONSTRAINT FKPJURPJUR01 FOREIGN KEY(Lista de campos) REFERENCES REAC.la otra tabla (lista de campos de la otra tabla));

ALTER TABLE REAC_PJUR#ERROR ADD (A_COMENTARIO VARCHAR2(200));
ALTER TABLE REAC_PJUR#ERROR ADD (CONSTRAINT FKPJURPJUR01 FOREIGN KEY(Lista de campos) REFERENCES REAC.la otra tabla (lista de campos de la otra tabla));

ALTER TABLE REAC_PJUR#ERROR ADD (A_COMENTARIO VARCHAR2(200));
ALTER TABLE REAC_PJUR#ERROR ADD (CONSTRAINT FKPJURPJUR01 FOREIGN KEY(Lista de campos) REFERENCES REAC.la otra tabla (lista de campos de la otra tabla));

ALTER TABLE REAC_PJUR#ERROR ADD (A_COMENTARIO VARCHAR2(200));
ALTER TABLE REAC_PJUR#ERROR ADD (CONSTRAINT FKPJURPJUR01 FOREIGN KEY(Lista de campos) REFERENCES REAC.la otra tabla (lista de campos de la otra tabla));

ALTER TABLE REAC_PJUR#ERROR ADD (A_COMENTARIO VARCHAR2(200));
ALTER TABLE REAC_PJUR#ERROR ADD (CONSTRAINT FKPJURPJUR01 FOREIGN KEY(Lista de campos) REFERENCES REAC.la otra tabla (lista de campos de la otra tabla));

ALTER TABLE REAC_PJUR#ERROR ADD (A_COMENTARIO VARCHAR2(200));
ALTER TABLE REAC_PJUR#ERROR ADD (CONSTRAINT FKPJURPJUR01 FOREIGN KEY(Lista de campos) REFERENCES REAC.la otra tabla (lista de campos de la otra tabla));

ALTER TABLE REAC_PJUR#ERROR ADD (A_COMENTARIO VARCHAR2(200));
ALTER TABLE REAC_PJUR#ERROR ADD (CONSTRAINT FKPJURPJUR01 FOREIGN KEY(Lista de campos) REFERENCES REAC.la otra tabla (lista de campos de la otra tabla));

ALTER TABLE REAC_PJUR#ERROR ADD (A_COMENTARIO VARCHAR2(200));
ALTER TABLE REAC_PJUR#ERROR ADD (CONSTRAINT FKPJURPJUR01 FOREIGN KEY(Lista de campos) REFERENCES REAC.la otra tabla (lista de campos de la otra tabla));

ALTER TABLE REAC_PJUR#ERROR ADD (A_COMENTARIO VARCHAR2(200));
ALTER TABLE REAC_PJUR#ERROR ADD (CONSTRAINT FKPJURPJUR01 FOREIGN KEY(Lista de campos) REFERENCES REAC.la otra tabla (lista de campos de la otra tabla));

ALTER TABLE REAC_PJUR#ERROR ADD (A_COMENTARIO VARCHAR2(200));
ALTER TABLE REAC_PJUR#ERROR ADD (CONSTRAINT FKPJURPJUR01 FOREIGN KEY(Lista de campos) REFERENCES REAC.la otra tabla (lista de campos de la otra tabla));

ALTER TABLE REAC_PJUR#ERROR ADD (A_COMENTARIO VARCHAR2(200));
ALTER TABLE REAC_PJUR#ERROR ADD (CONSTRAINT FKPJURPJUR01 FOREIGN KEY(Lista de campos) REFERENCES REAC.la otra tabla (lista de campos de la otra tabla));

ALTER TABLE REAC_PJUR#ERROR ADD (A_COMENTARIO VARCHAR2(200));
ALTER TABLE REAC_PJUR#ERROR ADD (CONSTRAINT FKPJURPJUR01 FOREIGN KEY(Lista de campos) REFERENCES REAC.la otra tabla (lista de campos de la otra tabla));

