ALTER TABLE REAC_LIBRO DROP CONSTRAINT FKLIBRCOMU01;

ALTER TABLE REAC_LIBRO DROP CONSTRAINT FKLIBRCOMU01;

ALTER TABLE REAC_LIBRO DROP CONSTRAINT FKLIBRCOMU01;

ALTER TABLE REAC_LIBRO DROP CONSTRAINT FKLIBRCOMU01;

ALTER TABLE REAC_LIBRO DROP CONSTRAINT FKLIBRCOMU01;

ALTER TABLE REAC_LIBRO DROP CONSTRAINT FKLIBRCOMU01;

ALTER TABLE REAC_LIBRO DROP CONSTRAINT FKLIBRCOMU01;

ALTER TABLE REAC_LIBRO DROP CONSTRAINT FKLIBRCOMU01;

ALTER TABLE REAC_LIBRO DROP CONSTRAINT FKLIBRCOMU01;

ALTER TABLE REAC_LIBRO DROP CONSTRAINT FKLIBRCOMU01;

ALTER TABLE REAC_LIBRO DROP CONSTRAINT FKLIBRCOMU01;

ALTER TABLE REAC_LIBRO DROP CONSTRAINT FKLIBRCOMU01;

ALTER TABLE REAC_LIBRO DROP CONSTRAINT FKLIBRCOMU01;

ALTER TABLE REAC_LIBRO DROP CONSTRAINT FKLIBRCOMU01;

