ALTER TABLE SARC_RECUPERA_DOE ADD (A_APELLIDO_1 VARCHAR2(50), A_APELLIDO_2 VARCHAR2(50), A_NOMBRE VARCHAR2(50), C_NIF VARCHAR2(9));
ALTER TABLE SARC_RECUPERA_DOE MODIFY (A_USUARIO  NULL, C_IDDOE VARCHAR2(13) NOT NULL, F_CREACION VARCHAR2(8));
ALTER TABLE SARC_RECUPERA_DOE DROP CONSTRAINT SARC_RECUPERA_DOE_PK;

ALTER TABLE SARC_RECUPERA_DOE ADD (CONSTRAINT CKUSUARIO CHECK ((A_USUARIO &lt;> NULL) OR (C_NIF &lt;> NULL)));

ALTER TABLE SARC_RECUPERA_DOE ADD (A_APELLIDO_1 VARCHAR2(50), A_APELLIDO_2 VARCHAR2(50), A_NOMBRE VARCHAR2(50), C_NIF VARCHAR2(9));
ALTER TABLE SARC_RECUPERA_DOE MODIFY (A_USUARIO  NULL, C_IDDOE VARCHAR2(13) NOT NULL, F_CREACION VARCHAR2(8));
ALTER TABLE SARC_RECUPERA_DOE DROP CONSTRAINT SARC_RECUPERA_DOE_PK;

ALTER TABLE SARC_RECUPERA_DOE ADD (CONSTRAINT CKUSUARIO CHECK ((A_USUARIO &lt;> NULL) OR (C_NIF &lt;> NULL)));

ALTER TABLE SARC_RECUPERA_DOE ADD (A_APELLIDO_1 VARCHAR2(50), A_APELLIDO_2 VARCHAR2(50), A_NOMBRE VARCHAR2(50), C_NIF VARCHAR2(9));
ALTER TABLE SARC_RECUPERA_DOE MODIFY (A_USUARIO  NULL, C_IDDOE VARCHAR2(13) NOT NULL, F_CREACION VARCHAR2(8));
ALTER TABLE SARC_RECUPERA_DOE DROP CONSTRAINT SARC_RECUPERA_DOE_PK;

ALTER TABLE SARC_RECUPERA_DOE ADD (CONSTRAINT CKUSUARIO CHECK ((A_USUARIO &lt;> NULL) OR (C_NIF &lt;> NULL)));

ALTER TABLE SARC_RECUPERA_DOE ADD (A_APELLIDO_1 VARCHAR2(50), A_APELLIDO_2 VARCHAR2(50), A_NOMBRE VARCHAR2(50), C_NIF VARCHAR2(9));
ALTER TABLE SARC_RECUPERA_DOE MODIFY (A_USUARIO  NULL, C_IDDOE VARCHAR2(13) NOT NULL, F_CREACION VARCHAR2(8));
ALTER TABLE SARC_RECUPERA_DOE DROP CONSTRAINT SARC_RECUPERA_DOE_PK;

ALTER TABLE SARC_RECUPERA_DOE ADD (CONSTRAINT CKUSUARIO CHECK ((A_USUARIO &lt;> NULL) OR (C_NIF &lt;> NULL)));

ALTER TABLE SARC_RECUPERA_DOE ADD (A_APELLIDO_1 VARCHAR2(50), A_APELLIDO_2 VARCHAR2(50), A_NOMBRE VARCHAR2(50), C_NIF VARCHAR2(9));
ALTER TABLE SARC_RECUPERA_DOE MODIFY (A_USUARIO  NULL, C_IDDOE VARCHAR2(13) NOT NULL, F_CREACION VARCHAR2(8));
ALTER TABLE SARC_RECUPERA_DOE DROP CONSTRAINT SARC_RECUPERA_DOE_PK;

ALTER TABLE SARC_RECUPERA_DOE ADD (CONSTRAINT CKUSUARIO CHECK ((A_USUARIO &lt;> NULL) OR (C_NIF &lt;> NULL)));

ALTER TABLE SARC_RECUPERA_DOE ADD (A_APELLIDO_1 VARCHAR2(50), A_APELLIDO_2 VARCHAR2(50), A_NOMBRE VARCHAR2(50), C_NIF VARCHAR2(9));
ALTER TABLE SARC_RECUPERA_DOE MODIFY (A_USUARIO  NULL, C_IDDOE VARCHAR2(13) NOT NULL, F_CREACION VARCHAR2(8));
ALTER TABLE SARC_RECUPERA_DOE DROP CONSTRAINT SARC_RECUPERA_DOE_PK;

ALTER TABLE SARC_RECUPERA_DOE ADD (CONSTRAINT CKUSUARIO CHECK ((A_USUARIO &lt;> NULL) OR (C_NIF &lt;> NULL)));

ALTER TABLE SARC_RECUPERA_DOE ADD (A_APELLIDO_1 VARCHAR2(50), A_APELLIDO_2 VARCHAR2(50), A_NOMBRE VARCHAR2(50), C_NIF VARCHAR2(9));
ALTER TABLE SARC_RECUPERA_DOE MODIFY (A_USUARIO  NULL, C_IDDOE VARCHAR2(13) NOT NULL, F_CREACION VARCHAR2(8));
ALTER TABLE SARC_RECUPERA_DOE DROP CONSTRAINT SARC_RECUPERA_DOE_PK;

ALTER TABLE SARC_RECUPERA_DOE ADD (CONSTRAINT CKUSUARIO CHECK ((A_USUARIO &lt;> NULL) OR (C_NIF &lt;> NULL)));

ALTER TABLE SARC_RECUPERA_DOE ADD (A_APELLIDO_1 VARCHAR2(50), A_APELLIDO_2 VARCHAR2(50), A_NOMBRE VARCHAR2(50), C_NIF VARCHAR2(9));
ALTER TABLE SARC_RECUPERA_DOE MODIFY (A_USUARIO  NULL, C_IDDOE VARCHAR2(13) NOT NULL, F_CREACION VARCHAR2(8));
ALTER TABLE SARC_RECUPERA_DOE DROP CONSTRAINT SARC_RECUPERA_DOE_PK;

ALTER TABLE SARC_RECUPERA_DOE ADD (CONSTRAINT CKUSUARIO CHECK ((A_USUARIO &lt;> NULL) OR (C_NIF &lt;> NULL)));

ALTER TABLE SARC_RECUPERA_DOE ADD (A_APELLIDO_1 VARCHAR2(50), A_APELLIDO_2 VARCHAR2(50), A_NOMBRE VARCHAR2(50), C_NIF VARCHAR2(9));
ALTER TABLE SARC_RECUPERA_DOE MODIFY (A_USUARIO  NULL, C_IDDOE VARCHAR2(13) NOT NULL, F_CREACION VARCHAR2(8));
ALTER TABLE SARC_RECUPERA_DOE DROP CONSTRAINT SARC_RECUPERA_DOE_PK;

ALTER TABLE SARC_RECUPERA_DOE ADD (CONSTRAINT CKUSUARIO CHECK ((A_USUARIO &lt;> NULL) OR (C_NIF &lt;> NULL)));

