ALTER TABLE SARC_ALEGACIONES ADD (F_CREACION VARCHAR2(8), F_MODIF DATE, U_CREACION VARCHAR2(8), U_MODIF VARCHAR2(8));
ALTER TABLE SARC_ALEGACIONES DROP CONSTRAINT CKALEPRE;
ALTER TABLE SARC_ALEGACIONES ADD (CONSTRAINT CKALEPRE CHECK (C_PRESENTADOR IN ('C','E')))
ALTER TABLE SARC_ALEGACIONES ADD (F_CREACION VARCHAR2(8), F_MODIF DATE, U_CREACION VARCHAR2(8), U_MODIF VARCHAR2(8));
ALTER TABLE SARC_ALEGACIONES DROP CONSTRAINT CKALEPRE;
ALTER TABLE SARC_ALEGACIONES ADD (CONSTRAINT CKALEPRE CHECK (C_PRESENTADOR IN ('C','E')))
ALTER TABLE SARC_ALEGACIONES ADD (F_CREACION VARCHAR2(8), F_MODIF DATE, U_CREACION VARCHAR2(8), U_MODIF VARCHAR2(8));
ALTER TABLE SARC_ALEGACIONES DROP CONSTRAINT CKALEPRE;
ALTER TABLE SARC_ALEGACIONES ADD (CONSTRAINT CKALEPRE CHECK (C_PRESENTADOR IN ('C','E')))
ALTER TABLE SARC_ALEGACIONES ADD (F_CREACION VARCHAR2(8), F_MODIF DATE, U_CREACION VARCHAR2(8), U_MODIF VARCHAR2(8));
ALTER TABLE SARC_ALEGACIONES DROP CONSTRAINT CKALEPRE;
ALTER TABLE SARC_ALEGACIONES ADD (CONSTRAINT CKALEPRE CHECK (C_PRESENTADOR IN ('C','E')))
ALTER TABLE SARC_ALEGACIONES ADD (F_CREACION VARCHAR2(8), F_MODIF DATE, U_CREACION VARCHAR2(8), U_MODIF VARCHAR2(8));
ALTER TABLE SARC_ALEGACIONES DROP CONSTRAINT CKALEPRE;
ALTER TABLE SARC_ALEGACIONES ADD (CONSTRAINT CKALEPRE CHECK (C_PRESENTADOR IN ('C','E')))
ALTER TABLE SARC_ALEGACIONES ADD (F_CREACION VARCHAR2(8), F_MODIF DATE, U_CREACION VARCHAR2(8), U_MODIF VARCHAR2(8));
ALTER TABLE SARC_ALEGACIONES DROP CONSTRAINT CKALEPRE;
ALTER TABLE SARC_ALEGACIONES ADD (CONSTRAINT CKALEPRE CHECK (C_PRESENTADOR IN ('C','E')))
ALTER TABLE SARC_ALEGACIONES ADD (F_CREACION VARCHAR2(8), F_MODIF DATE, U_CREACION VARCHAR2(8), U_MODIF VARCHAR2(8));
ALTER TABLE SARC_ALEGACIONES DROP CONSTRAINT CKALEPRE;
ALTER TABLE SARC_ALEGACIONES ADD (CONSTRAINT CKALEPRE CHECK (C_PRESENTADOR IN ('C','E')))
ALTER TABLE SARC_ALEGACIONES ADD (F_CREACION VARCHAR2(8), F_MODIF DATE, U_CREACION VARCHAR2(8), U_MODIF VARCHAR2(8));
ALTER TABLE SARC_ALEGACIONES DROP CONSTRAINT CKALEPRE;
ALTER TABLE SARC_ALEGACIONES ADD (CONSTRAINT CKALEPRE CHECK (C_PRESENTADOR IN ('C','E')))
ALTER TABLE SARC_ALEGACIONES ADD (F_CREACION VARCHAR2(8), F_MODIF DATE, U_CREACION VARCHAR2(8), U_MODIF VARCHAR2(8));
ALTER TABLE SARC_ALEGACIONES DROP CONSTRAINT CKALEPRE;
ALTER TABLE SARC_ALEGACIONES ADD (CONSTRAINT CKALEPRE CHECK (C_PRESENTADOR IN ('C','E')))
