ALTER TABLE SARC_REPORTS ADD (C_TIPO_ORGANO VARCHAR2(1), F_CREACION VARCHAR2(8), F_MODIF DATE, U_CREACION VARCHAR2(8), U_MODIF VARCHAR2(8));
ALTER TABLE SARC_REPORTS MODIFY (C_TIPO_CORREO NUMBER(2, 0));
ALTER TABLE SARC_REPORTS ADD (CONSTRAINT Constraint de sistema CHECK (C_TIPO_ORGANO IN ('C', 'U')));

ALTER TABLE SARC_REPORTS ADD (C_TIPO_ORGANO VARCHAR2(1), F_CREACION VARCHAR2(8), F_MODIF DATE, U_CREACION VARCHAR2(8), U_MODIF VARCHAR2(8));
ALTER TABLE SARC_REPORTS MODIFY (C_TIPO_CORREO NUMBER(2, 0));
ALTER TABLE SARC_REPORTS ADD (CONSTRAINT Constraint de sistema CHECK (C_TIPO_ORGANO IN ('C', 'U')));

ALTER TABLE SARC_REPORTS ADD (C_TIPO_ORGANO VARCHAR2(1), F_CREACION VARCHAR2(8), F_MODIF DATE, U_CREACION VARCHAR2(8), U_MODIF VARCHAR2(8));
ALTER TABLE SARC_REPORTS MODIFY (C_TIPO_CORREO NUMBER(2, 0));
ALTER TABLE SARC_REPORTS ADD (CONSTRAINT Constraint de sistema CHECK (C_TIPO_ORGANO IN ('C', 'U')));

ALTER TABLE SARC_REPORTS ADD (C_TIPO_ORGANO VARCHAR2(1), F_CREACION VARCHAR2(8), F_MODIF DATE, U_CREACION VARCHAR2(8), U_MODIF VARCHAR2(8));
ALTER TABLE SARC_REPORTS MODIFY (C_TIPO_CORREO NUMBER(2, 0));
ALTER TABLE SARC_REPORTS ADD (CONSTRAINT Constraint de sistema CHECK (C_TIPO_ORGANO IN ('C', 'U')));

ALTER TABLE SARC_REPORTS ADD (C_TIPO_ORGANO VARCHAR2(1), F_CREACION VARCHAR2(8), F_MODIF DATE, U_CREACION VARCHAR2(8), U_MODIF VARCHAR2(8));
ALTER TABLE SARC_REPORTS MODIFY (C_TIPO_CORREO NUMBER(2, 0));
ALTER TABLE SARC_REPORTS ADD (CONSTRAINT Constraint de sistema CHECK (C_TIPO_ORGANO IN ('C', 'U')));

ALTER TABLE SARC_REPORTS ADD (C_TIPO_ORGANO VARCHAR2(1), F_CREACION VARCHAR2(8), F_MODIF DATE, U_CREACION VARCHAR2(8), U_MODIF VARCHAR2(8));
ALTER TABLE SARC_REPORTS MODIFY (C_TIPO_CORREO NUMBER(2, 0));
ALTER TABLE SARC_REPORTS ADD (CONSTRAINT Constraint de sistema CHECK (C_TIPO_ORGANO IN ('C', 'U')));

ALTER TABLE SARC_REPORTS ADD (C_TIPO_ORGANO VARCHAR2(1), F_CREACION VARCHAR2(8), F_MODIF DATE, U_CREACION VARCHAR2(8), U_MODIF VARCHAR2(8));
ALTER TABLE SARC_REPORTS MODIFY (C_TIPO_CORREO NUMBER(2, 0));
ALTER TABLE SARC_REPORTS ADD (CONSTRAINT Constraint de sistema CHECK (C_TIPO_ORGANO IN ('C', 'U')));

ALTER TABLE SARC_REPORTS ADD (C_TIPO_ORGANO VARCHAR2(1), F_CREACION VARCHAR2(8), F_MODIF DATE, U_CREACION VARCHAR2(8), U_MODIF VARCHAR2(8));
ALTER TABLE SARC_REPORTS MODIFY (C_TIPO_CORREO NUMBER(2, 0));
ALTER TABLE SARC_REPORTS ADD (CONSTRAINT Constraint de sistema CHECK (C_TIPO_ORGANO IN ('C', 'U')));

ALTER TABLE SARC_REPORTS ADD (C_TIPO_ORGANO VARCHAR2(1), F_CREACION VARCHAR2(8), F_MODIF DATE, U_CREACION VARCHAR2(8), U_MODIF VARCHAR2(8));
ALTER TABLE SARC_REPORTS MODIFY (C_TIPO_CORREO NUMBER(2, 0));
ALTER TABLE SARC_REPORTS ADD (CONSTRAINT Constraint de sistema CHECK (C_TIPO_ORGANO IN ('C', 'U')));

